version: '3.2'

services:
  mysql:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: "mysql --user=root --password=root --execute 'show databases;'"
      interval: 15s
      timeout: 30s
      retries: 3
  redis:
    image: redis:4.0.13
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 30s
      retries: 3

networks:
  default:
    ipam:
      config:
        - subnet: 172.177.88.0/24